### ISSUE TITLE
Add Nested Pages, Change Navigation Layout

### ISSUE THREAD

**Issue by GeorgeBerdovskiy** [PureChart/purechart-documentation#1]
## Background
Right now, we only have one level of pages on our documentation site. In other words, there are no _subpages_ or _nested pages_. For better organization, we'd like to add them! You can find nested pages on many documentation sites, such as the Next.JS docs ([here](https://nextjs.org/docs/app/building-your-application/routing)).

<img width="1624" alt="Screen Shot 2024-03-10 at 2 45 23 PM" src="https://github.com/PureChart/purechart-documentation/assets/43429820/a8dccd26-063e-412f-87ba-2fc726678a17">

<img width="1624" alt="Screen Shot 2024-03-10 at 2 45 58 PM" src="https://github.com/PureChart/purechart-documentation/assets/43429820/ed865fc5-bafa-4f7e-9232-99652b96f97c">

As you can see in the above screenshots, there is a "Routing" page, but there are also many pages associated with "Routing" that appear below, such as "Defining Routes."

## Goal
Add nested pages to the PureChart documentation site ([here](https://docs.purechart.org/articles#getting-started)).

<img width="1624" alt="Screen Shot 2024-03-10 at 2 48 28 PM" src="https://github.com/PureChart/purechart-documentation/assets/43429820/6ffd6c92-61bd-4b37-a8ea-a28ce48481b6">

For example, we would like to have a separate page for every kind of chart to appear _under_ the "Types of Charts" page. Here's an example of what that may look like -

<img width="805" alt="image" src="https://github.com/PureChart/purechart-documentation/assets/43429820/57c67e74-07ef-4845-a8e1-6471a30a1834">

This will require some creative HTML and CSS so don't be afraid to be unorthodox. Good luck!

**Comment by GeorgeBerdovskiy** [comment]
You can keep the actual navigation mechanics identical and add all the buttons manually - no need for fancy stuff yet.

**Comment by ethanwithnoe** [comment]
I can do this one
